### ISSUE TITLE
Add support for DATA frame with null payload

### ISSUE THREAD

**Issue by cmebarrow** [reaktivity/nukleus.spec#20]
In order to transmit Data extension data without necessarily transmitting a message (i.e. payload) we need to change the core.idl Data frame definition to the following:
```
       struct Data extends core::stream::AuthorizedFrame [0x00000002]
        {
            int32 length;
            octets[length] payload = null;
            octets extension;
        }
```
This should have minimum downstream impact since the payload currently is mandatory so all nuklei must specify it (even if it's length 0). The above change means it will default to being null (length = -1). Nuklei will need to handle the possibility of the payload being null (or at least those which support extension-data only Data frames).

**Comment by jfallows** [comment]
This is supported.
