### ISSUE TITLE
Increase allowed size for data frames

### ISSUE THREAD

**Issue by cmebarrow** [reaktivity/nukleus.spec#8]
Currently limited to 255 (uint8 size of the octets data type). See [core.idl](https://github.com/reaktivity/nukleus.spec/blob/develop/src/main/resources/META-INF/reaktivity/core.idl) and [OctetsFlyweightGenerator](https://github.com/reaktivity/nukleus-maven-plugin/blob/develop/src/main/java/org/reaktivity/nukleus/maven/plugin/internal/generate/OctetsFlyweightGenerator.java).

**Comment by jfallows** [comment]
This is directly related to reaktivity/nukleus-maven-plugin#9.

**Comment by cmebarrow** [comment]
Proposal from our discussion today (changes to core.idl):
- Add data length as a four bytes header field to the data frame
- Eliminate the octets type
- Remove extensions from all frames

The reasoning for the above is that there is no added value in the octets type. The original need for it arose from the desire to allow extensions in data frames, but that requirement can be met simply by indicating the data length as a header field. That way any excess data in the message beyond that data length represents extension data.

**Comment by dpwspoon** [comment]
I hit this today with the HTTP begin frame, and headers being over the 256 size.

**Comment by jfallows** [comment]
Now that reaktivity/nukleus-maven-plugin#9 is completed, we can update `core.idl` to defer `payload` length to `length` field.

```
        struct Data extends core::stream::Frame [0x00000002]
        {
            int32 length;
            octets[length] payload;
            octets extension;
        }
```
